// Code generated by MockGen. DO NOT EDIT.
// Source: GoWeb/repository/interface (interfaces: ICacheRep)

// Package mock is a generated GoMock package.
package mock

import (
	service "GoWeb/models/service"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICacheRep is a mock of ICacheRep interface.
type MockICacheRep struct {
	ctrl     *gomock.Controller
	recorder *MockICacheRepMockRecorder
}

// MockICacheRepMockRecorder is the mock recorder for MockICacheRep.
type MockICacheRepMockRecorder struct {
	mock *MockICacheRep
}

// NewMockICacheRep creates a new mock instance.
func NewMockICacheRep(ctrl *gomock.Controller) *MockICacheRep {
	mock := &MockICacheRep{ctrl: ctrl}
	mock.recorder = &MockICacheRepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICacheRep) EXPECT() *MockICacheRepMockRecorder {
	return m.recorder
}

// DeleteCtx mocks base method.
func (m *MockICacheRep) DeleteCtx(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCtx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCtx indicates an expected call of DeleteCtx.
func (mr *MockICacheRepMockRecorder) DeleteCtx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCtx", reflect.TypeOf((*MockICacheRep)(nil).DeleteCtx), arg0, arg1)
}

// GetTokenByIDCtx mocks base method.
func (m *MockICacheRep) GetTokenByIDCtx(arg0 context.Context, arg1 string) (*service.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByIDCtx", arg0, arg1)
	ret0, _ := ret[0].(*service.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByIDCtx indicates an expected call of GetTokenByIDCtx.
func (mr *MockICacheRepMockRecorder) GetTokenByIDCtx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByIDCtx", reflect.TypeOf((*MockICacheRep)(nil).GetTokenByIDCtx), arg0, arg1)
}

// SetTokenCtx mocks base method.
func (m *MockICacheRep) SetTokenCtx(arg0 context.Context, arg1 string, arg2 int, arg3 *service.Claims) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTokenCtx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTokenCtx indicates an expected call of SetTokenCtx.
func (mr *MockICacheRepMockRecorder) SetTokenCtx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTokenCtx", reflect.TypeOf((*MockICacheRep)(nil).SetTokenCtx), arg0, arg1, arg2, arg3)
}
