// Code generated by MockGen. DO NOT EDIT.
// Source: GoWeb/repository/interface (interfaces: IMemberRepo)

// Package mock is a generated GoMock package.
package mock

import (
	repository "GoWeb/models/repository"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIMemberRepo is a mock of IMemberRepo interface.
type MockIMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIMemberRepoMockRecorder
}

// MockIMemberRepoMockRecorder is the mock recorder for MockIMemberRepo.
type MockIMemberRepoMockRecorder struct {
	mock *MockIMemberRepo
}

// NewMockIMemberRepo creates a new mock instance.
func NewMockIMemberRepo(ctrl *gomock.Controller) *MockIMemberRepo {
	mock := &MockIMemberRepo{ctrl: ctrl}
	mock.recorder = &MockIMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMemberRepo) EXPECT() *MockIMemberRepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIMemberRepo) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockIMemberRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIMemberRepo)(nil).Close))
}

// Disable mocks base method.
func (m *MockIMemberRepo) Disable(arg0 context.Context, arg1 *repository.UpdateMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockIMemberRepoMockRecorder) Disable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockIMemberRepo)(nil).Disable), arg0, arg1)
}

// Find mocks base method.
func (m *MockIMemberRepo) Find(arg0 context.Context, arg1, arg2 *string) (*repository.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1, arg2)
	ret0, _ := ret[0].(*repository.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIMemberRepoMockRecorder) Find(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIMemberRepo)(nil).Find), arg0, arg1, arg2)
}

// FindAll mocks base method.
func (m *MockIMemberRepo) FindAll(arg0 context.Context) (*[]repository.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(*[]repository.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIMemberRepoMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIMemberRepo)(nil).FindAll), arg0)
}

// Insert mocks base method.
func (m *MockIMemberRepo) Insert(arg0 context.Context, arg1 *repository.Member) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIMemberRepoMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIMemberRepo)(nil).Insert), arg0, arg1)
}

// Updates mocks base method.
func (m *MockIMemberRepo) Updates(arg0 context.Context, arg1 *repository.UpdateMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockIMemberRepoMockRecorder) Updates(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockIMemberRepo)(nil).Updates), arg0, arg1)
}
