postgres:
  Host: 192.168.XX.XX
  Port: 5432
  User: admin
  Password: admin
  Dbname: admin_db
  Schema: public
  Sslmode: false
  PgDriver: postgres

redis:
  RedisAddr: 192.168.17.57:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0
  AcctCacheTTL: 3